server:
  port: 8888

spring:
  application:
    name: config-test-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inseo24/config_test_repository.git
          username: inseo24
          password: secret

management:
  endpoints:
    web:
      exposure:
        include: health
