server:
  port: 8888

spring:
  application:
    name: config-test-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inseo24/config_test_repository.git
          # 공개 레포라 비밀번호 필요 없는 듯. ㅋ.ㅋ

management:
  endpoints:
    web:
      exposure:
        include: health
